name: Android Conferences

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Speed-up by Restoring Gradle Cache from Previous Builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*')}}
          restore-keys: |
            ${{runner.os}}-gradle-

      - name: Build project
        run: ./gradlew assembleDebug

      - name: Uploading APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/**.apk
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zimperium
        uses: zimperium/zscanmarketplace@master
        timeout-minutes: 60
        with:
        # REPLACE: Zimperium Client Environment Name
          client_env: ziap
        # REPLACE: Zimperium Client ID
          client_id: xtGeJrz6SF-LvcVJ6Mi5SQ
        # REPLACE: Zimperium Client Secret
          client_secret: ${{ secrets.ZSCAN_CLIENT_SECRET }}
        # REPLACE: The path to an .ipa or .apk
          app_file: app-debug.apk

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: Zimperium.sarif

      - name: Move Sarif
        uses: actions/upload-artifact@v3
        with:
          name: sarif
          path: Zimperium.sarif
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          
